apiVersion: v1
entries:
  octo-mesh:
  - apiVersion: v2
    appVersion: 3.1.156.0
    created: "2024-08-26T02:06:51.0913195Z"
    description: OctoMesh Data refinery helm chart
    digest: 439a9d442c52c92d7504aa7eef6c6ed126c3395ff220008faff2c0c91b7a9d97
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    maintainers:
    - email: support@meshmakers.io
      name: meshmakers
    name: octo-mesh
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-3.1.156.tgz
    version: 3.1.156
  - apiVersion: v2
    appVersion: 3.1.150.0
    created: "2024-08-26T02:06:51.0907932Z"
    description: OctoMesh Data refinery helm chart
    digest: 105e23c9ea1d264a336ea1ccff9f5865ef3c79d385e562a08de4e2a46cdf3d5c
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    name: octo-mesh
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-3.1.150.tgz
    version: 3.1.150
  - apiVersion: v2
    appVersion: 3.1.147.0
    created: "2024-08-26T02:06:51.0897411Z"
    description: OctoMesh Data refinery helm chart
    digest: 409ef1361bb57cba9a560ebd8b3518c4bcbcaf453a717438994324b6fe978e18
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    name: octo-mesh
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-3.1.147.tgz
    version: 3.1.147
  - apiVersion: v2
    appVersion: 3.1.146.0
    created: "2024-08-26T02:06:51.0886937Z"
    description: OctoMesh Data refinery helm chart
    digest: 4786a6c2c4c26017e99befe9d168ce31dbb8c04eaf4b8a329cf927ebca75579b
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    name: octo-mesh
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-3.1.146.tgz
    version: 3.1.146
  - apiVersion: v2
    appVersion: 3.1.145.0
    created: "2024-08-26T02:06:51.087647Z"
    description: OctoMesh Data refinery helm chart
    digest: a4ce9609ad15bca72d3e3bafe0b4a016eb4416709a7283c8b5e22398aae5b5b9
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    name: octo-mesh
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-3.1.145.tgz
    version: 3.1.145
  - apiVersion: v2
    appVersion: 3.1.143.0
    created: "2024-08-26T02:06:51.0865989Z"
    description: OctoMesh Data refinery helm chart
    digest: 5beeeb09d72f125c069edf2e5195dd446ac895afbdfe64cb2e3803f46093e3b9
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    name: octo-mesh
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-3.1.143.tgz
    version: 3.1.143
  - apiVersion: v2
    appVersion: 3.1.140.0
    created: "2024-08-26T02:06:51.0841396Z"
    description: OctoMesh Data refinery helm chart
    digest: 9aa707da80e8a1b8b9c95ff572786aa45dcf54ed702707905dadd916824e1d53
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    name: octo-mesh
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-3.1.140.tgz
    version: 3.1.140
  - apiVersion: v2
    appVersion: 3.1.136.0
    created: "2024-08-26T02:06:51.0831072Z"
    description: OctoMesh Data refinery helm chart
    digest: dd018acae9831173716fbe1de5a263ab6a37cc27dafaa6f79baf426f1146c584
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    name: octo-mesh
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-3.1.136.tgz
    version: 3.1.136
  - apiVersion: v2
    appVersion: 3.1.134.0
    created: "2024-08-26T02:06:51.0820569Z"
    description: OctoMesh Data refinery helm chart
    digest: 48e9e6f44e99cae12ff9a55563e4776399ec9a89dbc46335bb5b3078fe9835ac
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    name: octo-mesh
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-3.1.134.tgz
    version: 3.1.134
  - apiVersion: v2
    appVersion: 3.1.118.0
    created: "2024-08-26T02:06:51.0804816Z"
    description: OctoMesh Data refinery helm chart
    digest: c45bc0ac6483f71c618552147314c5a63f37747f2c2e8393b312d6c041d8113c
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    name: octo-mesh
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-3.1.118.tgz
    version: 3.1.118
  - apiVersion: v2
    appVersion: 3.1.117.0
    created: "2024-08-26T02:06:51.0794307Z"
    description: OctoMesh Data refinery helm chart
    digest: 34d242184ebeac32c77e28c8ead7b69b50c13d9bf6bda08966f3f1d5f6293c83
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    name: octo-mesh
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-3.1.117.tgz
    version: 3.1.117
  - apiVersion: v2
    appVersion: 3.1.116.0
    created: "2024-08-26T02:06:51.078382Z"
    description: OctoMesh Data refinery helm chart
    digest: f93ac340222c12b5520d8083a53fc6b7c201bd2d83994509bfb739bf6fb4caa0
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    name: octo-mesh
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-3.1.116.tgz
    version: 3.1.116
  - apiVersion: v2
    appVersion: 3.1.112.0
    created: "2024-08-26T02:06:51.0773173Z"
    description: OctoMesh Data refinery helm chart
    digest: c8cb21d3046b3768a4426d8440bf9ac5908fd20482953378c8c7863a45f91793
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    name: octo-mesh
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-3.1.112.tgz
    version: 3.1.112
  - apiVersion: v2
    appVersion: 3.1.88.0
    created: "2024-08-26T02:06:51.099592Z"
    description: OctoMesh Data refinery helm chart
    digest: 603ec2decb27a98affe415e4d4683799b78cdcf6720a32646e531ae56a51955d
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    name: octo-mesh
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-3.1.88.tgz
    version: 3.1.88
  - apiVersion: v2
    appVersion: 3.1.87.0
    created: "2024-08-26T02:06:51.0965623Z"
    description: OctoMesh Data refinery helm chart
    digest: c8c7f6ae01e4b8657e9bccc3d3403d612c1bd6e86c2aff52e69c8470ad4d2b3f
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    name: octo-mesh
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-3.1.87.tgz
    version: 3.1.87
  - apiVersion: v2
    appVersion: 3.1.86.0
    created: "2024-08-26T02:06:51.094995Z"
    description: OctoMesh Data refinery helm chart
    digest: 830367ae7d1baa717c7719006b624ffc6752ac94b55947faa38bcb13aa83877c
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    name: octo-mesh
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-3.1.86.tgz
    version: 3.1.86
  - apiVersion: v2
    appVersion: 3.1.85.0
    created: "2024-08-26T02:06:51.0939614Z"
    description: OctoMesh Data refinery helm chart
    digest: 654bacd67ad4064b31efa9c3ea7586fd9df488b5de76b3ceb4e8c06b1844d635
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    name: octo-mesh
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-3.1.85.tgz
    version: 3.1.85
  - apiVersion: v2
    appVersion: 3.1.84.0
    created: "2024-08-26T02:06:51.0934336Z"
    description: OctoMesh Data refinery helm chart
    digest: 8a1168049b7bb541817717963d89cb87db9136bab99697830607663834d82a77
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    name: octo-mesh
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-3.1.84.tgz
    version: 3.1.84
  - apiVersion: v2
    appVersion: 3.1.83.0
    created: "2024-08-26T02:06:51.0923668Z"
    description: OctoMesh Data refinery helm chart
    digest: 40ace170b5cb885145bc3774f10d97a0ee53e780413ced49324ef58e0668fc93
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    name: octo-mesh
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-3.1.83.tgz
    version: 3.1.83
  - apiVersion: v2
    appVersion: 0.0.2405.28009
    created: "2024-08-26T02:06:51.0762741Z"
    description: OctoMesh Data refinery helm chart
    digest: b63621b03bbdd8cace8184fbe9652881ba54e9db464dbe81b7d72e7ab4509b5c
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    name: octo-mesh
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-0.0.2405.tgz
    version: 0.0.2405
  - apiVersion: v2
    appVersion: 3.1.158.0
    created: "2024-08-26T02:06:51.0752249Z"
    description: OctoMesh Data refinery helm chart
    digest: 6b53442f12c9f4ae8854fdbd0775b3432389248ed30217780accc2ed8defc78d
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    maintainers:
    - email: support@meshmakers.io
      name: meshmakers
    name: octo-mesh
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-0.0.0.tgz
    version: 0.0.0
  octo-mesh-adapter:
  - apiVersion: v2
    appVersion: 3.1.156.0
    created: "2024-08-26T02:06:51.1051244Z"
    description: An adapter for the OctoMesh Data refinery
    digest: 7c150cfa0fa13cd22675834579f6d360a35bd9b13ab08a14a28b62c523c3ffab
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    maintainers:
    - email: support@meshmakers.io
      name: meshmakers
    name: octo-mesh-adapter
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-adapter-3.1.156.tgz
    version: 3.1.156
  - apiVersion: v2
    appVersion: 3.1.150.0
    created: "2024-08-26T02:06:51.1051244Z"
    description: An adapter for the OctoMesh Data refinery
    digest: 72832d97ab3ff30feaed1302d3bc1afe7f9ac40276088dd5a6781b65271d96ab
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    name: octo-mesh-adapter
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-adapter-3.1.150.tgz
    version: 3.1.150
  - apiVersion: v2
    appVersion: 3.1.147.0
    created: "2024-08-26T02:06:51.1051244Z"
    description: An adapter for the OctoMesh Data refinery
    digest: f57e370b4d84441c239a7e46e90091088908ca50096bdd779af45cb4549b954b
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    name: octo-mesh-adapter
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-adapter-3.1.147.tgz
    version: 3.1.147
  - apiVersion: v2
    appVersion: 3.1.146.0
    created: "2024-08-26T02:06:51.1051244Z"
    description: An adapter for the OctoMesh Data refinery
    digest: b1f121aa879526e566c5e994557f77d5b89e2aff9bf2bdc701f5a45888ac42c3
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    name: octo-mesh-adapter
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-adapter-3.1.146.tgz
    version: 3.1.146
  - apiVersion: v2
    appVersion: 3.1.145.0
    created: "2024-08-26T02:06:51.1051244Z"
    description: An adapter for the OctoMesh Data refinery
    digest: 9b599008f121bb172e8a53d05fb7c7d393606bb2413c9a08764f40b8f892ee5f
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    name: octo-mesh-adapter
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-adapter-3.1.145.tgz
    version: 3.1.145
  - apiVersion: v2
    appVersion: 3.1.143.0
    created: "2024-08-26T02:06:51.099592Z"
    description: An adapter for the OctoMesh Data refinery
    digest: 69cbc520797bc21da6e1e32b146abb6b53cf419ee99109c5acaa5014734eec4d
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    name: octo-mesh-adapter
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-adapter-3.1.143.tgz
    version: 3.1.143
  - apiVersion: v2
    appVersion: 3.1.140.0
    created: "2024-08-26T02:06:51.099592Z"
    description: An adapter for the OctoMesh Data refinery
    digest: dfe0764822fb45e48c4c0ae75066ffbbd1f9eda3b3354ad1f663bdb87bcd0177
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    name: octo-mesh-adapter
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-adapter-3.1.140.tgz
    version: 3.1.140
  - apiVersion: v2
    appVersion: 3.1.136.0
    created: "2024-08-26T02:06:51.099592Z"
    description: An adapter for the OctoMesh Data refinery
    digest: 26504093c7b46efbe1fc2607f5fa818909ba4618194f1bfdd4c33d6d5f3b6ffa
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    name: octo-mesh-adapter
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-adapter-3.1.136.tgz
    version: 3.1.136
  - apiVersion: v2
    appVersion: 3.1.134.0
    created: "2024-08-26T02:06:51.099592Z"
    description: An adapter for the OctoMesh Data refinery
    digest: 9985d48d7e71501f62df87db997d959bab81f732d52404598e37cd75cc407de2
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    name: octo-mesh-adapter
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-adapter-3.1.134.tgz
    version: 3.1.134
  - apiVersion: v2
    appVersion: 3.1.118.0
    created: "2024-08-26T02:06:51.099592Z"
    description: An adapter for the OctoMesh Data refinery
    digest: 2784adebc25e2db30bd6b25da8a46718f54eac0cae104cfbd43c7ea126e758b8
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    name: octo-mesh-adapter
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-adapter-3.1.118.tgz
    version: 3.1.118
  - apiVersion: v2
    appVersion: 3.1.117.0
    created: "2024-08-26T02:06:51.099592Z"
    description: An adapter for the OctoMesh Data refinery
    digest: 4901ed73a693cba48a54eedd632cbd9517e3875c86e0d3b177aa8466afa5393f
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    name: octo-mesh-adapter
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-adapter-3.1.117.tgz
    version: 3.1.117
  - apiVersion: v2
    appVersion: 3.1.116.0
    created: "2024-08-26T02:06:51.099592Z"
    description: An adapter for the OctoMesh Data refinery
    digest: 4b67756d910cfffdd1c494abc7a944cdd75f2e31e02614e707591f2b7e4a87f5
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    name: octo-mesh-adapter
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-adapter-3.1.116.tgz
    version: 3.1.116
  - apiVersion: v2
    appVersion: 3.1.112.0
    created: "2024-08-26T02:06:51.099592Z"
    description: An adapter for the OctoMesh Data refinery
    digest: f65d2b8ed805e6b75e3d1d04d0a4e8fdbfe9d5cd532a6901aab9a150732064f2
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    name: octo-mesh-adapter
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-adapter-3.1.112.tgz
    version: 3.1.112
  - apiVersion: v2
    appVersion: 3.1.88.0
    created: "2024-08-26T02:06:51.1051244Z"
    description: An adapter for the OctoMesh Data refinery
    digest: d7063ee1dd41fa06796fd49f305e600e1e8bad9c4d4a5fd74c534be0edb599f8
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    name: octo-mesh-adapter
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-adapter-3.1.88.tgz
    version: 3.1.88
  - apiVersion: v2
    appVersion: 3.1.158.0
    created: "2024-08-26T02:06:51.099592Z"
    description: An adapter for the OctoMesh Data refinery
    digest: 75fbded61aa97977fdf4758bb7b002775dd1ddbd57d8e808389475c85efd3ff6
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    maintainers:
    - email: support@meshmakers.io
      name: meshmakers
    name: octo-mesh-adapter
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-adapter-0.0.0.tgz
    version: 0.0.0
  octo-mesh-communication-operator:
  - apiVersion: v2
    appVersion: 3.1.156.0
    created: "2024-08-26T02:06:51.1051244Z"
    dependencies:
    - condition: octo-mesh-crds.enabled
      name: octo-mesh-crds
      repository: file://../octo-mesh-crds
      version: ~3.1.0
    description: The OctoMesh Communication Operator that manages plugs and sockets
    digest: 74e66adcb84c2f8818c0a130dd68cb88cdbdcfecbad819b09c4bd9b90425862a
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    maintainers:
    - email: support@meshmakers.io
      name: meshmakers
    name: octo-mesh-communication-operator
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-communication-operator-3.1.156.tgz
    version: 3.1.156
  - apiVersion: v2
    appVersion: 3.1.158.0
    created: "2024-08-26T02:06:51.1051244Z"
    dependencies:
    - condition: octo-mesh-crds.enabled
      name: octo-mesh-crds
      repository: file://../octo-mesh-crds
      version: ~3.1.0
    description: The OctoMesh Communication Operator that manages plugs and sockets
    digest: ec70dfeace739e936c4c5bac77f8719b85941cf1499fcc0e2532800a3748d033
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    maintainers:
    - email: support@meshmakers.io
      name: meshmakers
    name: octo-mesh-communication-operator
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-communication-operator-0.0.0.tgz
    version: 0.0.0
  octo-mesh-crds:
  - apiVersion: v2
    appVersion: 3.1.156.0
    created: "2024-08-26T02:06:51.1051244Z"
    description: Custom Resource Definitions for OctoMesh
    digest: 4c62ffc161d98b9ec24dd2cb9a8d2e5410a4578128bf29153eba530b6434b228
    maintainers:
    - email: support@meshmakers.io
      name: meshmakers
    name: octo-mesh-crds
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-crds-3.1.156.tgz
    version: 3.1.156
  - apiVersion: v2
    appVersion: 3.1.158.0
    created: "2024-08-26T02:06:51.1051244Z"
    description: Custom Resource Definitions for OctoMesh
    digest: 094d4daf144a9f7b8c89d5d01519dce6769d8e62af6af4fe4953567ebe669854
    maintainers:
    - email: support@meshmakers.io
      name: meshmakers
    name: octo-mesh-crds
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-crds-0.0.0.tgz
    version: 0.0.0
generated: "2024-08-26T02:06:51.0736087Z"
