apiVersion: v1
entries:
  octo-mesh:
  - apiVersion: v2
    appVersion: 3.1.85.0
    created: "2024-05-31T06:30:44.5721815Z"
    description: OctoMesh Data refinery helm chart
    digest: 654bacd67ad4064b31efa9c3ea7586fd9df488b5de76b3ceb4e8c06b1844d635
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    name: octo-mesh
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-3.1.85.tgz
    version: 3.1.85
  - apiVersion: v2
    appVersion: 3.1.84.0
    created: "2024-05-31T06:30:44.5721815Z"
    description: OctoMesh Data refinery helm chart
    digest: 8a1168049b7bb541817717963d89cb87db9136bab99697830607663834d82a77
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    name: octo-mesh
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-3.1.84.tgz
    version: 3.1.84
  - apiVersion: v2
    appVersion: 3.1.83.0
    created: "2024-05-31T06:30:44.5721815Z"
    description: OctoMesh Data refinery helm chart
    digest: 40ace170b5cb885145bc3774f10d97a0ee53e780413ced49324ef58e0668fc93
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    name: octo-mesh
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-3.1.83.tgz
    version: 3.1.83
  - apiVersion: v2
    appVersion: 0.0.2405.28009
    created: "2024-05-31T06:30:44.5721815Z"
    description: OctoMesh Data refinery helm chart
    digest: b63621b03bbdd8cace8184fbe9652881ba54e9db464dbe81b7d72e7ab4509b5c
    icon: https://raw.githubusercontent.com/meshmakers/octo-helm/main/assets/meshmakers64.png
    name: octo-mesh
    type: application
    urls:
    - https://meshmakers.github.io/charts/octo-mesh-0.0.2405.tgz
    version: 0.0.2405
generated: "2024-05-31T06:30:44.5721815Z"
